- name: mongodb
  hosts: mongodb 
  become: yes
  tasks:
  - name: copy mongodb repo
    ansible.builtin.copy:
     src: mongodb.repo
     dest: /etc/yum.repos.d/mongodb.repo
  - name: Install Mongodb
    ansible.bulitin.package:
     name: mongodb-org
     state: present